# Generated by Django 6.0.3 on 2026-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='executado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='mensagem_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('executado', 'Executado'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
