# Generated by Django 6.0.3 on 2026-03-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registro_executado_em_registro_mensagem_erro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='importacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='registros.importacaoplanilha'),
        ),
    ]
