# Generated by Django 6.0.3 on 2026-03-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_importacaoplanilha_registro_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoplanilha',
            name='status',
            field=models.CharField(choices=[('processando', 'Processando'), ('concluida', 'Concluida'), ('erro', 'Erro')], default='processando', max_length=20),
        ),
        migrations.AddField(
            model_name='importacaoplanilha',
            name='total_registros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
