# Generated by Django 6.0.3 on 2026-03-12 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='erro_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='mensagem_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='sucesso_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='target_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='arquivo_planilha',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL),
        ),
    ]
