# Generated by Django 6.0.3 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_execution_erro_count_execution_mensagem_erro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluida'), ('error', 'Erro')], default='pending', max_length=20),
        ),
    ]
