# Generated by Django 6.0.3 on 2026-03-16 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_alter_execution_status'),
        ('registros', '0004_importacaoplanilha_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='importacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='registros.importacaoplanilha'),
        ),
        migrations.CreateModel(
            name='ResultadoExecucaoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('executado', 'Executado'), ('erro', 'Erro')], max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('executado_em', models.DateTimeField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='automations.execution')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_execucao', to='registros.registro')),
            ],
        ),
    ]
